version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging application for deployment...
      - mkdir -p deployment
      - cp target/twig-*-core.jar deployment/
      - cp Dockerfile deployment/
      - cp -r scripts deployment/
      - cp appspec.yml deployment/

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - Dockerfile
    - target/twig-*-core.jar
  base-directory: deployment
